# PHPのバージョンは8.1
runtime: php82
# スタンダード環境を指定
env: standard

runtime_config:
  document_root: public
  php_version: 8.2

automatic_scaling:
  min_idle_instances: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  # ログのエラーが出ないようにするための記述
  LOG_CHANNEL: stderr
  # キャッシュのエラーが出ないようにするための記述
  CACHE_DIRECTORY: /tmp/laravel/cache
  SESSION_DRIVER: cookie
  APP_STORAGE: /tmp

# デプロイ時のcomposerのバージョン
build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.7.7
